CREATE TABLE `rentinfo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `rentalAddress` varchar(100) NOT NULL,
  `rentalCity` varchar(100) NOT NULL,
  `rentalZip` varchar(10) NOT NULL,
  `ownerFirstName` varchar(100) DEFAULT NULL,
  `ownerLastName` varchar(100) DEFAULT NULL,
  `ownerAddress` varchar(100) DEFAULT NULL,
  `ownerCity` varchar(100) DEFAULT NULL,
  `ownerState` varchar(100) DEFAULT NULL,
  `ownerZip` varchar(10) DEFAULT NULL,
  `ownerPhone1` varchar(20) DEFAULT NULL COMMENT '(nnn)nnn-nnnn',
  `ownerPhone2` varchar(20) DEFAULT NULL,
  `ownerEmail` varchar(200) DEFAULT NULL,
  `renterAccount` varchar(20) DEFAULT NULL COMMENT 'if rented the renterXXX values will be filled',
  `renterFirstName` varchar(100) DEFAULT NULL,
  `renterLastName` varchar(100) DEFAULT NULL,
  `renterPhone1` varchar(20) DEFAULT NULL,
  `renterPhone2` varchar(20) DEFAULT NULL,
  `renterEmail` varchar(200) DEFAULT NULL,
  `leaseStartDate` date DEFAULT NULL COMMENT 'leases are 3, 6, 12, 24 or 1 for month to month',
  `leaseEndDate` date DEFAULT NULL,
  `rentalStatus` varchar(20) DEFAULT NULL COMMENT 'vacant, notVacant, lastMonth',
  `accessStatus` varchar(20) DEFAULT NULL COMMENT 'lockboxBlack, lockboxGray, key, appointment',
  `notes` text,
  `created` datetime DEFAULT NULL,
  `lasttime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;